feat:  add generation of the adverts markup
htmlacademy-javascript/576665-keksobooking-22 pull request #5
Opened 2021-02-15 19:21 UTC by Nadiiya

2021-02-16 07:52 UTC, Shramkoweb requested changes

2021-02-16 07:52 UTC, Shramkoweb commented on js/card.js
> +  const total = document.createDocumentFragment();
```suggestion
  const featureElement = document.createDocumentFragment(); ?
```

2021-02-16 07:52 UTC, Shramkoweb commented on js/card.js
> +  const total = document.createDocumentFragment();
galleryElement

2021-02-16 07:52 UTC, Shramkoweb commented on js/card.js
> +const createTypeNameFrom = (type) => {
Похоже на словарь

Обратите внимание, что не все объекты в коде проекта должны быть перечислениями. Например, допускается использование объектов в качестве словарей:

const priceTypeToRange = {
  low: 'до 200 ₽',
  medium: 'от 200 ₽ до 500 ₽',
  high: 'от 500 ₽',
};

Можно сделать проще через обьект и дай правильное имя как для словаря

2021-02-16 07:52 UTC, Shramkoweb commented on js/card.js
> +    cardTitle.remove();
Я бы вынес это в ф-ю. Ты проверяешь есть ли данные, если они есть сетитшь куда -то их или удалаешь текущий елемент.

2021-02-16 07:52 UTC, Shramkoweb commented on js/card.js
> +    cardTitle.remove();
Только надо подумать как такую ф-ю красиво написать)

2021-02-16 07:52 UTC, Shramkoweb commented on js/card.js
> +const createCardsList = (parent, data) => {
`data` - так себе имя. Не понятно, что за дата?

2021-02-16 07:52 UTC, Shramkoweb commented on js/main.js
> +const cardsListParent = document.querySelector('#map-canvas');
`cardsListParent ` ? Почему судя по классу - это карта, может так ее лучше и назвать?

2021-02-16 09:39 UTC, Nadiiya commented on js/card.js
> +  const total = document.createDocumentFragment();
createGalleryElement
так?

2021-02-16 09:41 UTC, Nadiiya commented on js/card.js
> +    cardTitle.remove();
Да, согласна.

2021-02-16 09:48 UTC, Nadiiya commented on js/card.js
> +const createCardsList = (parent, data) => {
data - в смысле исходные данные
advertsData

2021-02-16 10:02 UTC, Nadiiya commented on js/main.js
> +const cardsListParent = document.querySelector('#map-canvas');
В задании сказано 

> Эта разметка в будущем будет вставляться в интерактивную карту, а пока, на время разработки, мы её будем отображать блоке с картой.

мне не очень понятно пока, что это будет за элемент, поэтому такая абстракция вышла )))

2021-02-16 10:36 UTC, Shramkoweb commented on js/card.js
> +  const total = document.createDocumentFragment();
galleryElement - это к 13 строчке

По поводу ф-и самой, да можно createGalleryElement

2021-02-16 10:36 UTC, Shramkoweb commented on js/card.js
> +const createCardsList = (parent, data) => {
data - слишком абстрактно.

advertsData или просто adverts

2021-02-16 10:38 UTC, Shramkoweb commented on js/main.js
> +const cardsListParent = document.querySelector('#map-canvas');
**отображать блоке с картой.** - значит 5 строчка кода, это `map` или что-тол вроде `mapCanvas`

2021-02-18 07:27 UTC, Shramkoweb approved these changes
Как по мне многовасто ф-й которые прям уж слишком специализированны. 
Их сложно будет переиспользовать, но это не критично.

2021-02-18 07:28 UTC, Shramkoweb commented on js/util.js
> +export {appendContent};
```suggestion
export {getRandomInteger, getRandomDecimal, appendContent};
```

2021-02-18 07:28 UTC, merged