Module6 task1
htmlacademy-javascript/576665-keksobooking-22 pull request #6
Opened 2021-02-21 19:38 UTC by Nadiiya

2021-02-21 20:40 UTC, Shramkoweb requested changes

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +/* global L:readonly */
Это что?

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +const toggleDisable = (element, classname) => {
`toggle` - обычно говорит о переключении двух состояний. 
Включить/Выключить - у тебя же только выключает, если я верно понля.

Это что-то вроде `disableFormElement`

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +).addTo(map);
Я бы создал ф-ю что-то вроде `initMap` и в ней бы получал обьект `map` и отрисовывал карту.

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +const createMainPinMarker = () => {
Хорошо было бы чтобы эта ф-я рендера пина получала параметры **как** и **где** его рисовать. Сейчас же она замыкает все внутри себя через область видимости - оно работатет, но не очень)

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +const createMainPinMarker = () => {
+ иконку тоже можно получить как параметр, а не внутри рендерить

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +  const similarAdvertIcon = L.marker({
Аналогично

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +  });
Что-то тут все смешалось. Я аж запутался - попробуй обьяснить мне, что тут происходит?

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +addressInput.setAttribute('readonly', '');
```suggestion
addressInput.readOnly = false;
```

??

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +addressInput.value = getMainMarkerLocation(mainPinMarker, defaultLocation);
Получается эта ф-я сразу и отдает значение `return location` ? И сама же навечно, вешает слушатель на главный пин ? `mainPinMarker.on` ?

Лучше наоборот. Создать ф-ю которая обрабатывает движение пине

`handleMainPinMove` - она будет записывать данные в `addressInput` внутри себя

```
const handleMainPinMove = (evt) => {
  const {lat, lng} = evt.target.getLatLng();

  addressInput.value = `${lat.toFixed(5)}, ${lng.toFixed(5)}`;
};

const setDefaultLocation = (input, defaultLocation) => {
  const {lat, lng} = defaultLocation;
  
  input.value = `${lat}, ${lng}`;
}

setDefaultLocation();
mainPinMarker.on('moveend', handleMainPinMove);

```

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +addressInput.value = getMainMarkerLocation(mainPinMarker, defaultLocation);
Вдруг чего не ясно, что я тут написал - то не стесняйся, пиши =)

2021-02-21 20:40 UTC, Shramkoweb commented on js/map.js
> +addressInput.value = getMainMarkerLocation(mainPinMarker, defaultLocation);
Кстати   lat.toFixed(5) - пятерка -это магическое число. В константы =)

2021-02-21 20:42 UTC, Shramkoweb commented on js/map.js
> +addressInput.setAttribute('readonly', '');
Чуть лаконичнее ?

2021-02-22 15:42 UTC, Nadiiya commented on js/map.js
> +/* global L:readonly */
Это заклинание для линтера, иначе вот:
[http://prntscr.com/103wpg1](http://prntscr.com/103wpg1)

2021-02-22 15:53 UTC, Nadiiya commented on js/map.js
> +const toggleDisable = (element, classname) => {
Мне казалось, что она должна все же вкл/выкл. Но сейчас думаю, да, она только включает. Наверное, и в теле функции toggle на add нужно заменить?

2021-02-22 18:29 UTC, Nadiiya commented on js/map.js
> +  });
Для каждого элемента массива объявлений adverts:
стр 67-73 определить иконку и локейшен для метки
стр 75 - добавить метку на карту
стр 76 - привязать к метке балун
стр 77 - содержимое балуна - разметка объявления, котороая генерится ф-цией createCardItem()

2021-02-22 18:50 UTC, Shramkoweb commented on js/map.js
> +    marker
А чего тут нет пустой строки - тут же уже другой метод вызваем?

2021-02-22 19:33 UTC, Shramkoweb approved these changes

2021-02-22 19:33 UTC, Shramkoweb commented on js/map.js
> +  return map;
Тут можно отступ:

Обычно я так делаю в ф-и:
Блок которые подготавливает все данные

Блок кода которые что-то полезное делает

return

2021-02-22 19:33 UTC, merged