Module7 task1
htmlacademy-javascript/576665-keksobooking-22 pull request #7
Opened 2021-03-05 12:53 UTC by Nadiiya

2021-03-05 17:45 UTC, Shramkoweb requested changes

2021-03-05 17:45 UTC, Shramkoweb commented on js/api.js
> +    .catch(() => {
Тут лучше получить саму ошибку

2021-03-05 17:45 UTC, Shramkoweb commented on js/api.js
> +      onFail()
Сюда потом ее передать, и возможно вывести юзеру?

2021-03-05 17:45 UTC, Shramkoweb commented on js/api.js
> +        onFail();
Аналогично

2021-03-05 17:45 UTC, Shramkoweb commented on js/form.js
> +}
```suggestion
const resetAdvertForm = (evt) => {
  evt.preventDefault();
  advertForm.reset();
  setDefaultLocation(advertFormAddress, defaultLocation);
}
```

2021-03-05 17:45 UTC, Shramkoweb commented on js/form.js
> +});
```suggestion
resetButton.addEventListener('click',resetAdvertForm);
```

2021-03-05 17:45 UTC, Shramkoweb commented on js/form.js
> +});
Вроде не должно ничего сломать и более чисто как по мне?

2021-03-05 17:45 UTC, Shramkoweb commented on js/form.js
> +  document.removeEventListener('keydown', (evt) => {
removeEventListener ждет `ССЫЛКУ` на ф-ю  обработчик которую ты хочешь удалить.
А тут у тебя анонимная функция, он ничего не удалит.

2021-03-05 17:45 UTC, Shramkoweb commented on js/form.js
> +    modalCloseButton.addEventListener('click', () => {
Аналогично - не удалит ничего

2021-03-05 17:45 UTC, Shramkoweb commented on js/main.js
> +advertFormSubmit();
```suggestion
import {advertFormSubmit} from './form.js';

advertFormSubmit();
```

2021-03-05 17:45 UTC, Shramkoweb commented on js/map.js
> +import {defaultLocation} from './constants.js';
Ипорты идут до констант

2021-03-05 17:45 UTC, Shramkoweb commented on js/map.js
> +  (adverts) => createSimilarAdvertsMarkers(adverts),
Может вынести эти 2 функции отдельно, а не создавать их тут на лету?

2021-03-05 17:45 UTC, Shramkoweb commented on js/util.js
> +  }, ALERT_SHOW_TIME);
Зачем?

2021-03-05 17:45 UTC, Shramkoweb commented on js/util.js
> +  return evt.key === ('Escape' || 'Esc');
Проверяла работает ?
![image](https://user-images.githubusercontent.com/42001531/110153167-5d3d0a00-7deb-11eb-8f51-3d09760861a5.png)

2021-03-05 18:58 UTC, Nadiiya commented on js/form.js
> +});
а как же 16 строчка?
evt.preventDefault();

2021-03-05 19:20 UTC, Nadiiya commented on js/util.js
> +  }, ALERT_SHOW_TIME);
Сообщение информирует юзера об ошибке и исчезает через некоторое время.
?
Ответила?

2021-03-05 19:27 UTC, Nadiiya commented on js/util.js
> +  return evt.key === ('Escape' || 'Esc');
![Screenshot_4](https://user-images.githubusercontent.com/40362768/110164130-9bd9c100-7df9-11eb-8b48-b0586431cfa2.jpg)

2021-03-05 19:41 UTC, Shramkoweb commented on js/util.js
> +  return evt.key === ('Escape' || 'Esc');
Ты не решила проблему - проверка у тебя всегда по 1 сроке, а надо по 2м

2021-03-05 20:08 UTC, Nadiiya commented on js/util.js
> +  return evt.key === ('Escape' || 'Esc');
>  а надо по 2м

Почему по 2-м? В зависимости от ОС один ИЛИ другой вариант?
`evt.key === ('Escape' || 'Esc');`

2021-03-07 09:26 UTC, Shramkoweb requested changes

2021-03-07 09:26 UTC, Shramkoweb commented on js/api.js
> +    .then (checkStatus)
А разве когда стату !ok мы же словим ошибку в `catch` зачем добавлять лишний then?

2021-03-07 09:26 UTC, Shramkoweb commented on js/form.js
> +const submitSuccessMessage = createPopup('#success', '.success');
Я бы их создавал прям во время `openErrorModal` или `openSuccessModal` так же можно?
А то сейчас у нас всегда лишняя одна модалка)

2021-03-07 09:26 UTC, Shramkoweb commented on js/main.js
> +import  './map.js';
```suggestion
import './map.js';
```

2021-03-07 09:45 UTC, Nadiiya commented on js/api.js
> +    .then (checkStatus)
checkStatus возвращает ошибку с кодом ответа сервера, если что-то пошло не так. Если словим ошибку в catch, получим
[http://prntscr.com/10f5czi](http://prntscr.com/10f5czi)

2021-03-07 09:55 UTC, Nadiiya commented on js/form.js
> +const submitSuccessMessage = createPopup('#success', '.success');
Не сможем, потому что они должны быть снаружи, чтобы быть доступными и для closeModal

2021-03-07 09:58 UTC, Shramkoweb approved these changes

2021-03-07 09:58 UTC, merged