feat: add form validation
htmlacademy-javascript/576665-keksobooking-22 pull request #8
Opened 2021-03-10 07:24 UTC by Nadiiya

2021-03-10 07:47 UTC, Nadiiya commented on js/validation.js
> +  const errorMessage = invalidityMessages.join('. \n');
Возможно, это лишнее, собирать сообщения в массив, и стоит отдавать в setCustomValidity одно сообщение.

2021-03-10 16:47 UTC, Shramkoweb requested changes

2021-03-10 16:47 UTC, Shramkoweb commented on js/form.js
> +  //TODO reset filter
На будущее?

2021-03-10 16:47 UTC, Shramkoweb commented on js/main.js
> +import './validation.js';
Опять неверно импортишь - мы же решили, что импортим ф-и и вызываем их тут
Карта аналогично

2021-03-10 16:47 UTC, Shramkoweb commented on js/validation.js
> +      options[i].setAttribute('disabled', '');
options[i].disabled = true

2021-03-10 16:47 UTC, Shramkoweb commented on js/validation.js
> +      options[i].setAttribute('selected', '');
options[i].selected = true

2021-03-10 16:47 UTC, Shramkoweb commented on js/validation.js
> +      options[i].removeAttribute('selected');
Аналогично ниже

2021-03-10 16:47 UTC, Shramkoweb commented on js/validation.js
> +  advertFormTimeOut.setAttribute('selected', '');
Как писал выше

2021-03-10 16:47 UTC, Shramkoweb commented on js/validation.js
> +  const errorMessage = invalidityMessages.join('. \n');
Иногда так делаю - это норм

2021-03-10 17:21 UTC, Nadiiya commented on js/form.js
> +  //TODO reset filter
да, чтоб не забыть

2021-03-10 19:14 UTC, Nadiiya commented on js/main.js
>  advertFormSubmit();
Получается, все другие ф-ции прямо или опосредовано завязаны на этой ф-ции. Я опасаюсь, что это неправильно. Вопрос про модульность.

2021-03-11 08:34 UTC, Shramkoweb approved these changes
LGTM

2021-03-11 08:34 UTC, merged